services:
  # Django web service
  - type: web
    name: django-taskmanager-api
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn django_taskmanager_api.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: django-taskmanager-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://your-frontend-app.onrender.com"
      - key: PYTHON_VERSION
        value: 3.10.0

# Database
databases:
  - name: django-taskmanager-db
    databaseName: taskmanager
    user: taskmanager 